
export default function translateService($translateProvider) {

    /** ENGLISH **/
    $translateProvider.translations('en', {
        'GLASSES': 'Glasses',
        'SEARCH': 'Search',
        'TAB_SEARCH': 'Glasses Search',
        'TAB_INVENTORY': 'Inventory',
        'TAB_IMPORT': 'Import',
        'TAB_EXPORT': 'Export',
        'TAB_INSTRUCTIONS': 'Instructions',
        'EYE': 'Eye',
        'RIGHT_EYE': 'Right Eye',
        'LEFT_EYE': 'Left Eye',
        'DOMINANT_EYE': 'Dominant Eye',
        'RIGHT': 'Right (OD)',
        'LEFT': 'Left (OS)',
        'NONE': 'None',
        'PATIENT_REFRACTION': 'Patient\'s Refraction',
        'PATIENT_NAME': 'Patient\'s Name',
        'NAME_OPTIONAL': 'Name (optional)',
        'SPHERE': 'Sphere',
        'CYLINDER': 'Cylinder',
        'AXIS': 'Axis',
        'ADD': 'ADD',
        'SPHERICAL_EQUIVALENT': 'Spherical Equivalent',
        'UNROUNDED': 'unrounded',
        'ROUNDED': 'rounded',
        'PAIR': 'Pair',
        'PAIR_NUMBER': 'Pair Number',
        'AVAILABLE': 'Available',
        'TAKE': 'Take',
        'TAKEN': 'Taken',
        'CLEAR': 'Clear', // as in 'clear input'
        'COMPACT': 'Compact',
        'FULL': 'Full',
        'SEARCH_GLASSES': 'Search Glasses',
        'SEARCH_INVENTORY': 'Search Inventory',
        'SEARCH_FIND': 'Find',
        'SEARCH_REFRACTION_NOTE': 'Please type in any minus (-) signs. Plus (+) signs are not necessary.',
        'SEARCH_HIDE_ADD': 'Hide matches with ADD',
        'SEARCH_HIDDEN_ADD': 'Hide ADD',
        'SEARCH_MATCHES': 'Find Matches',
        'SEARCH_CLEAR': 'Clear Search',
        'SEARCH_SPH_EQUIV': 'Search by Spherical Equivalent',
        'SEARCH_NOT_ENOUGH': 'Not enough matches?',
        'SEARCH_PREVIOUS': 'Previous Searches',
        'SEARCH_AVAILABLE': 'Available Glasses',
        'SEARCH_NUMBER_MATCHES': '# of Matches',
        'SEARCH_NOTE': 'NOTE: Better matches will have more cells highlighted in green for each row/pair of glasses.',
        'INVENTORY_TAKEN': 'Taken Pairs',
        'INVENTORY_AVAILABLE': 'Available Pairs',
        'IMPORT_INVENTORY': 'Import Inventory',
        'IMPORT_UPLOAD_HEADING': 'Upload a .csv or .json file',
        'IMPORT_INSTRUCTIONS': 'Instructions',
        'IMPORT_INSTRUCTIONS_L1': 'When importing pairs of glasses, ONLY the first row of data should contain header information.',
        'IMPORT_INSTRUCTIONS_L2': 'Remove all empty rows and prefix each pair number with the letter of the set. (example: Set C, Pair # 1 becomes "C1")',
        'IMPORT_INSTRUCTIONS_L3': 'The program accepts 3 different column set-ups for data (in specific order):',
        'IMPORT_COLS': 'columns',
        'IMPORT_COL_9': 'Right Sphere, Right Cylinder, Right Axis, Right Add, Left Sphere, Left Cylinder, Left Axis, Left Add, Pair Number',
        'IMPORT_COL_11': 'Pair Number, Right Sphere, Right Cylinder, Right Axis, Right Add, Right Trifocal, Left Sphere, Left Cylinder, Left Axis, Left Add, Left Trifocal',
        'IMPORT_COL_16': 'Right Sphere, Right Cylinder, Right SE Unrounded, Right SE Rounded, Right Axis, Right Axis Range, Right Add, Left Sphere, Left Cylinder, Left SE Unrounded, Left SE Rounded, Left Axis, Left Axis Range, Left Add, Pair Number, Taken Status',
        'IMPORT_HOVER': 'hover mouse over dotted underline for more info',
        'IMPORT_NOTE': 'NOTE:',
        'IMPORT_NOTE_DESC': 'Negative cylinders prescriptions will be converted to positive values.',
        'IMPORT_BUTTON': 'Import',
        'IMPORT_MANUAL': 'Enter manually',
        'IMPORT_MANUAL_ADD': 'Add Pair',
        'IMPORT_ADDED_GLASSES': 'Added Glasses',
        'EXPORT_INVENTORY': 'Export Inventory',
        'EXPORT_OPTIONS': 'Other Options',
        'EXPORT_FULL': 'Full Inventory',
        'EXPORT_FULL_COMPACT': 'Full Inventory Compact',
        'EXPORT_TAKEN': 'Taken Glasses',
        'EXPORT_AVAILABLE': 'Available Glasses',
        'EXPORT_CSV': '.CSV files can be opened in spreadsheet programs such as Microsoft Excel and Apple Numbers.',
        'EXPORT_JSON': '.JSON files are used by this program for debugging purposes. Both files can be imported into this program.',
        'EXPORT_COLS': 'columns of data',
        'EXPORT_FULL_DESC': 'Compact datasets contain',
        'EXPORT_FULL_TT': 'Right Sphere, Right Cylinder, Right SE Unrounded, Right SE Rounded, Right Axis, Right Axis Range, Right Add, Left Sphere, Left Cylinder, Left SE Unrounded, Left SE Rounded, Left Axis, Left Axis Range, Left Add, Pair Number, Taken Status',
        'EXPORT_COMPACT_DESC': 'Full CSV datasets contain',
        'EXPORT_COMPACT_TT': 'Right Sphere, Right Cylinder, Right Axis, Right Add, Left Sphere, Left Cylinder, Left Axis, Left Add, Pair Number, Taken Status',
        'RESET_DATABASE': 'Reset database',
        'RESET_WARNING': 'WARNING:',
        'RESET_WARNING_L1A': 'This resets the database and removes',
        'RESET_WARNING_ALL': 'ALL',
        'RESET_WARNING_L1B': 'pairs of glasses.',
        'RESET_WARNING_L2': 'Be sure to export glasses data above before resetting the database.',
        'RESET_WARNING_LAST': 'This is the only warning.',
        'DISPLAY_NO_ADDED_GLASSES': 'No glasses added this session.',
        'DISPLAY_NO_PREV_SEARCH': 'No previous searches this session.',
        'DISPLAY_NO_PAIRS': 'No pairs available.',
        'DISPLAY_NO_RESULTS': 'No results to display.',
        'DISPLAY_NOTHING': 'Nothing to display.',
        'LANG_ENGLISH': 'English',
        'LANG_SPANISH': 'Spanish'
    });

    /** SPANISH **/
    $translateProvider.translations('es', {
        'GLASSES': 'Lentes',
        'SEARCH': 'Buscar',
        'TAB_SEARCH': 'Buscar Lentes',
        'TAB_INVENTORY': 'Inventario',
        'TAB_IMPORT': 'Importar',
        'TAB_EXPORT': 'Guardar',
        'TAB_INSTRUCTIONS': 'Instrucciones',
        'EYE': 'Ojo',
        'RIGHT_EYE': 'Ojo Derecho',
        'LEFT_EYE': 'Ojo Izquierda',
        'DOMINANT_EYE': 'Ojo Dominante',
        'RIGHT': 'Derecho (OD)',
        'LEFT': 'Izquierda (OS)',
        'NONE': 'Ninguno',
        'PATIENT_REFRACTION': 'Paciente Refracción',
        'PATIENT_NAME': 'Paciente Nombre',
        'NAME_OPTIONAL': 'Nombre (opcional)',
        'REFRACTION': 'Refracción',
        'SPHERE': 'Esfera',
        'CYLINDER': 'Cilindro',
        'AXIS': 'Eje',
        'ADD': 'Adición',
        'SPHERICAL_EQUIVALENT': 'Equivalente esférico',
        'UNROUNDED': 'no redondeado',
        'ROUNDED': 'redondeado',
        'PAIR': 'Par de lentes',
        'PAIR_NUMBER': 'Número de par',
        'AVAILABLE': 'Disponibles',
        'TAKE': 'Entregar',
        'TAKEN': 'Entregados',
        'CLEAR': 'Borrar',
        'COMPACT': 'Datos compactos',
        'FULL': 'Datos completos',
        'SEARCH_GLASSES': 'Buscar Lentes',
        'SEARCH_INVENTORY': 'Inventario de búsqueda',
        'SEARCH_FIND': 'Encontrar',
        'SEARCH_REFRACTION_NOTE': 'Por favor escriba cualquier signo menos (-). Los signos más (+) no son necesarios.',
        'SEARCH_HIDE_ADD': 'Esconder coincidencias con adición',
        'SEARCH_HIDDEN_ADD': 'Escondido adición',
        'SEARCH_MATCHES': 'Encontrar coincidencias',
        'SEARCH_CLEAR': 'Borrar búsqueda ',
        'SEARCH_SPH_EQUIV': 'Búsqueda por equivalente esférico',
        'SEARCH_NOT_ENOUGH': 'No hay suficientes coincidencias?',
        'SEARCH_PREVIOUS': 'Búsquedas previas',
        'SEARCH_AVAILABLE': 'Par de lentes disponsibles',
        'SEARCH_NUMBER_MATCHES': '# de coincidencias',
        'SEARCH_NOTE': 'NOTA: Mejores coincidencias tienen más celdas resaltadas en verde para cada fila/par de lentes.',
        'INVENTORY_TAKEN': 'Par de lentes entregados',
        'INVENTORY_AVAILABLE': 'Par de lentes disponsibles',
        'IMPORT_INVENTORY': 'Inventario de importar',
        'IMPORT_UPLOAD_HEADING': 'Adjuntar un archivo .csv o .json',
        'IMPORT_INSTRUCTIONS': 'Instrucciones',
        'IMPORT_INSTRUCTIONS_L1': 'Al importar pares de gafas, SÓLO la primera fila de datos debe contener información del encabezado.',
        'IMPORT_INSTRUCTIONS_L2': 'Elimine todas las filas vacías y prefija cada número de par con la letra del conjunto. (ejemplo: Set C, el número de par 1 se convierte en "C1")',
        'IMPORT_INSTRUCTIONS_L3': 'El programa acepta 3 configuraciones diferentes de columna para datos (en orden específico):',
        'IMPORT_COLS': 'columnas',
        'IMPORT_COL_9': 'Esfera derecha, cilindro derecho, eje derecho, adición a la derecha, esfera izquierda, cilindro izquierdo, eje izquierdo, adición a la izquierda, número de par',
        'IMPORT_COL_11': 'Número de par, esfera derecha, cilindro derecho, eje derecho, adición a la derecha, trifocal derecha, esfera izquierda, cilindro izquierdo, eje izquierdo, adición a la izquierda, trifocal izquierda',
        'IMPORT_COL_16': 'Esfera derecha, cilindro derecho, equivalente esférico derecho no redondeado, equivalente esférico redondeado derecho, eje derecho, gama del eje derecho, adición a la derecha, esfera izquierda, cilindro izquierdo, equivalente esférico izquierdo no redondeado, izquierdo equivalente esférico redondeado, eje izquierdo, gama izquierda del eje, adición a la izquierda, número de par, estado entregado',
        'IMPORT_HOVER': 'coloca el cursor sobre el subrayado punteado para obtener más información',
        'IMPORT_NOTE': 'NOTA:',
        'IMPORT_NOTE_DESC': 'Las prescripciones de los cilindros negativos se convertirán automáticos en valores positivos.',
        'IMPORT_BUTTON': 'Adjuntar',
        'IMPORT_MANUAL': 'Agregar manualmente cada par de lentes',
        'IMPORT_MANUAL_ADD': 'Agregar',
        'IMPORT_ADDED_GLASSES': 'Lentes agregados',
        'EXPORT_INVENTORY': 'Inventario de guardar',
        'EXPORT_OPTIONS': 'Otras opciones',
        'EXPORT_FULL': 'Inventario completo de lentes',
        'EXPORT_FULL_COMPACT': 'Inventario completo de lentes compactos',
        'EXPORT_TAKEN': 'Par de lentes entregados',
        'EXPORT_AVAILABLE': 'Par de lentes disponsibles',
        'EXPORT_CSV': 'Los archivos .CSV se pueden abrir en programas de hojas de cálculo como Microsoft Excel y Apple Numbers.',
        'EXPORT_JSON': 'Los archivos .JSON son utilizados por este programa para fines de depuración. Ambos archivos se pueden importar a este programa.',
        'EXPORT_COLS': 'columnas de datos',
        'EXPORT_FULL_DESC': 'Los conjuntos de datos CSV completos contienen',
        'EXPORT_FULL_TT': 'Esfera derecha, cilindro derecho, equivalente esférico derecho no redondeado, equivalente esférico derecho redondeado, eje derecho, rango de eje derecho, adición a la derecha, esfera izquierda, cilindro izquierdo, equivalente esférico izquierda no redondeado, equivalente esférico izquierdo redondeado, eje izquierdo, rango de eje izquierdo, adición a la izquierda, número de par, estado entregado',
        'EXPORT_COMPACT_DESC': 'Los conjuntos de datos CSV compactos contienen',
        'EXPORT_COMPACT_TT': 'Esfera derecha, cilindro derecho, eje derecho, adición a la derecha, esfera izquierda, cilindro izquierdo, eje izquierdo, adición a la izquierda, número de par, estado entregado',
        'RESET_DATABASE': 'Formatear la base de datos',
        'RESET_WARNING': 'ADVERTENCIA:',
        'RESET_WARNING_L1A': 'Esto formatear la base de datos y elimina',
        'RESET_WARNING_L1B': 'los pares de lentes.',
        'RESET_WARNING_ALL': 'TODOS',
        'RESET_WARNING_L2': 'Asegúrese de exportar los datos de lentes anteriores antes de formatear la base de datos.',
        'RESET_WARNING_LAST': 'Esta es la ultima advertencia.',
        'DISPLAY_NO_ADDED_GLASSES': 'Sin lentes agregó esta sesión.',
        'DISPLAY_NO_PREV_SEARCH': 'No hay búsquedas previas en esta sesión.',
        'DISPLAY_NO_PAIRS': 'No hay pares de lentes disponibles.',
        'DISPLAY_NO_RESULTS': 'No hay resultados para mostrar.',
        'DISPLAY_NOTHING': 'Nada que mostrar.',
        'LANG_ENGLISH': 'Inglés',
        'LANG_SPANISH': 'Español'
    });

    $translateProvider.preferredLanguage('en');
    $translateProvider.useSanitizeValueStrategy('sceParameters');
}
